name             'code_generator'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/code_generator'
issues_url       'https://github.com/osuosl-cookbooks/code_generator/issues'
license          'Apache-2.0'
chef_version     '>= 17.0'
description      'Generates Chef code for the OSUOSL'
version          '1.0.8'

supports         'almalinux', '~> 8.0'
